Reduce logfile output in HEMCO, and combine Verbose and Warnings into a single switch
geoschem/HEMCO pull request #182
Opened 2022-12-06 22:12 UTC by yantosca

This is the PR corresponding to issue #180 and to https://github.com/geoschem/geos-chem/pull/1549.

In this PR we seek to:
1. Convert most HEMCO logfile output to debug-only printout
2. Consolidate Verbose and Warnings into a single logical switch in `HEMCO_Config.rc` (e.g. `Verbose: true`) so that warnings will also be toggled by Verbose.  There isn't much need for separate verbose & warnings levels any more. 

Tagging @lizziel @msulprizio

2022-12-06 22:48 UTC, yantosca commented
Also tagging @christophkeller

2022-12-08 20:45 UTC, yantosca commented
This PR is now ready for review.

2022-12-12 16:12 UTC, yantosca commented
Integration tests pending (with GEOS-Chem)

HEMCO standalone simulation log output (24hr run)
- with `Verbose: true:`  [HEMCO_sa.log.verbose.txt](https://github.com/geoschem/HEMCO/files/10209876/HEMCO_sa.log.verbose.txt)
- with `Verbose: false`:  [HEMCO_sa.log.noverbose.txt](https://github.com/geoschem/HEMCO/files/10209882/HEMCO_sa.log.noverbose.txt)

2022-12-13 16:03 UTC, msulprizio requested changes

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_config_mod.F90
> +   !INTEGER               :: verb
I recommend deleting this line to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_config_mod.F90
> +       !--------------------------------------------------------------------
I recommend deleting these lines to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_config_mod.F90
> +       !---------------------------------------------------------------------
I recommend deleting these lines to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_config_mod.F90
> +       !                    verb, warn, RC )
I recommend deleting these lines to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +       !WarningLevel =  0
I recommend deleting these lines to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +    !Err%Warnings     = WarningLevel
I recommend deleting this line to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +    !Err%nWarnings = 0
I recommend deleting this line to avoid confusion

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +! !DESCRIPTION: Returns true if the HEMCO verbose number is set to 3 or larger.
Do we need to remove the reference to '3' here?

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +!  TODO: Convert VERBOSE to a simple logical on/off switch.
Remove this line?

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +    ! Check if "Verbose: 3" was set in the HEMCO_Config.rc file
Remove reference to '3' here

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hco_error_mod.F90
> +       IF ( Err%LUN < 0 ) LUN = 6   ! ,,, or to stdout if file isn't open
remove `,,,` from comment here?

2022-12-13 16:03 UTC, msulprizio commented on src/Core/hcoio_read_std_mod.F90
> +       ! TODO: Merge warnings w/ verbose, and toggle with a simple on/off
Remove comment here?

2022-12-14 19:46 UTC, yantosca commented
@jimmielin: I have updated the program logic (in 5041a2000d5d35eb4670fa49303b34d28309edd3) so that HEMCO verbose will be toggled either with Verbose true/false, or with Verbose and Warnings having integer values.  See the section here:

```F90

! !LOCAL VARIABLES:
!
    ! Scalars
    LOGICAL               :: doVerbose,   found
    LOGICAL               :: foundVerb,   foundWarn
    LOGICAL               :: verboseBool
    INTEGER               :: I,           N,         POS
    INTEGER               :: verb,        warn

    ! Strings
    CHARACTER(LEN=255)    :: line
    CHARACTER(LEN=255)    :: loc
    CHARACTER(LEN=255)    :: LogFile
    CHARACTER(LEN=255)    :: DiagnPrefix
    CHARACTER(LEN=255)    :: MetField
    CHARACTER(LEN=255)    :: GridRes
    CHARACTER(LEN=512)    :: msg

    !======================================================================
    ! ReadSettings begins here
    !======================================================================

    ! Enter
    Loc = 'ReadSettings (hco_config_mod.F90)'

    ... etc ...
    !-----------------------------------------------------------------------
    ! Read settings and add them as options to core extensions
    !-----------------------------------------------------------------------

    ! Do until exit
    DO

       ! Read line
       CALL HCO_ReadLine ( IU_HCO, LINE, EOF, RC )
       IF ( RC /= HCO_SUCCESS ) THEN
          msg = 'Error in HEMCO_Config.rc @ line: ' // TRIM( Line )
          CALL HCO_Error( msg, RC, thisLoc=loc )
          RETURN
       ENDIF

       ! Return if EOF
       IF ( EOF ) EXIT

       ! Test if the Verbose flag is logical.  We need to know this ahead
       ! of time in order to avoid input errors (i.e. reading characters
       ! when integers are expected) in the code that follows below.
       !  -- Bob Yantosca (14 Dec 2022)
       IF ( INDEX( line, 'Verbose' ) > 0 ) THEN
          verboseBool = (                                                    &
             ( INDEX( line, 't' ) > 0 ) .or. ( INDEX( line, 'f' ) > 0 ) .or. &
             ( INDEX( line, 'T' ) > 0 ) .or. ( INDEX( line, 'F' ) > 0 )     )
       ENDIF

       ... etc...

       IF ( TRIM(LINE) == '' ) CYCLE

       ! Add this option to HEMCO core
       CALL AddExtOpt ( HcoConfig, TRIM(LINE), &
                        CoreNr, RC, IgnoreIfExist=.TRUE. )
       IF ( RC /= HCO_SUCCESS ) THEN
          msg = 'Error in HEMCO_Config.rc @ line: ' // TRIM( Line )
          CALL HCO_Error( msg, RC, thisLoc=loc )
          RETURN
       ENDIF

    ENDDO

    ... etc ...

    !-----------------------------------------------------------------------
    ! Initialize error object if needed.
    ! Extract values to initialize error module and set some further
    ! HEMCO variables. Only the first time the settings are read (settings
    ! can be read multiple times if nested HEMCO configuration files are
    ! used)
    !
    ! NOTE: In HEMCO 3.7.0, the Verbose and Warnings integers in the
    ! HEMCO_Config.rc file have been replaced with "Verbose: true".
    ! Update the logic to make the test for Verbose backwards compatible
    ! with HEMCO_Config.files prior to HEMCO 3.7.0.
    !   -- Bob Yantosca (14 Dec 2022)
    !-----------------------------------------------------------------------
    IF ( .NOT. ASSOCIATED(HcoConfig%Err) ) THEN

       ! Initialize
       doVerbose = .FALSE.
       verb      = 0
       warn      = 0

       ! Check if Verbose is a logical entry in HEMCO_Config.rc
       IF ( verboseBool ) THEN

          !-----------------------------------------------------------------
          ! "Verbose: true" or "Verbose: false" was found
          !-----------------------------------------------------------------

          ! First look for Verbose (logical).  This is now the default
          ! inthe HEMCO_Config.rc file for HEMCO 3.7.0 and later.
          CALL GetExtOpt( HcoConfig,            CoreNr,       'Verbose',     &
                          OptValBool=doVerbose, found=found,  RC=RC         )
          IF ( RC /= HCO_SUCCESS ) THEN
             msg = 'Error looking for "Verbose" (logical) in HEMCO_Config.rc!'
             CALL HCO_Error( msg, RC, thisLoc=loc )
             RETURN
          ENDIF

          ! Print status message
          IF ( doVerbose ) THEN
             msg = NEW_LINE( 'A' ) // 'HEMCO verbose output is ON'
          ELSE
             msg = NEW_LINE( 'A' ) // 'HEMCO verbose output is OFF'
          ENDIF
          CALL HCO_Msg( msg, verb=.TRUE. )

       ELSE

          !-----------------------------------------------------------------
          ! "Verbose: true" or "Verbose: false" was not found
          !-----------------------------------------------------------------

          ! Check for Verbose (integer)
          CALL GetExtOpt( HcoConfig,      CoreNr,          'Verbose',        &
                          OptValInt=verb, found=foundVerb,  RC=RC           )
          IF ( RC /= HCO_SUCCESS ) THEN
             msg = 'Error looking for "Verbose" (integer) in HEMCO_Config.rc!'
             CALL HCO_Error( msg, RC, thisLoc=loc )
             RETURN
          ENDIF

          IF ( foundVerb .and. verb > 0 ) THEN

             ! Toggle HEMCO verbose output on for nonzero integer values
             doVerbose = .TRUE.
             msg = NEW_LINE( 'A' )                                        // &
                  'HEMCO verbose output is ON.'                           // &
                   NEW_LINE( 'A' )                                        // &
                  'Numbered Verbose and Warning options are deprecated.'  // &
                   NEW_LINE( 'A' )                                        // &
                  'Please use "Verbose: true:" or "Verbose: false" for '  // &
                  'controlling verbose output.'
             CALL HCO_Msg( msg, verb=.TRUE. )

          ELSE

             ! Verbose (logical) and Verbose (integer) were not found,
             ! now look for Warnings (integer)
             CALL GetExtOpt( HcoConfig,      CoreNr,         'Warnings',     &
                             OptValInt=warn, found=foundWarn, RC=RC         )
             IF ( RC /= HCO_SUCCESS ) THEN
                msg = &
                 'Error looking for "Warnings" (integer) in HEMCO_Config.rc!'
                CALL HCO_Error( msg, RC, thisLoc=loc )
                RETURN
             ENDIF
             IF ( foundWarn .and. warn > 0 ) THEN

                ! Toggle HEMCO verbose output on
                ! (Verbose = 0; Warnings > 0)
                doVerbose = .TRUE.
                msg =                                                        &
                   NEW_LINE( 'A' )                                        // &
                  'HEMCO verbose output is ON.'                           // &
                   NEW_LINE( 'A' )                                        // &
                  'Numbered Verbose and Warning options are deprecated.'  // &
                   NEW_LINE( 'A' )                                        // &
                  'Please use "Verbose: true:" or "Verbose: false" for '  // &
                  'controlling verbose output.'
                CALL HCO_Msg( msg, verb=.TRUE. )

             ELSE

                ! Toggle HEMCO verbose off
                ! (Verbose: false, Verbose = 0 and Warnings = 0)
                doVerbose = .FALSE.
                msg =                                                        &
                   NEW_LINE( 'A' )                                        // &
                  'HEMCO verbose output is OFF.'                          // &
                   NEW_LINE( 'A' )                                        // &
                  'Numbered Verbose and Warning options are deprecated.'  // &
                   NEW_LINE( 'A' )                                        // &
                  'Please use "Verbose: true:" or "Verbose: false" for '  // &
                  'controlling ver [...]

2022-12-14 19:48 UTC, yantosca commented on src/Core/hco_config_mod.F90
> +   !INTEGER               :: verb
We now actually use this variable in the new program logic (see commit 5041a2000d5d35eb4670fa49303b34d28309edd3)

2022-12-14 19:49 UTC, yantosca commented on src/Core/hco_config_mod.F90
> +       !--------------------------------------------------------------------
This has been removed in the updating of program logic (see commit 5041a2000d5d35eb4670fa49303b34d28309edd3).

2022-12-14 19:50 UTC, yantosca commented on src/Core/hco_config_mod.F90
> +       !---------------------------------------------------------------------
This has been removed in the updating of program logic (see commit https://github.com/geoschem/HEMCO/commit/5041a2000d5d35eb4670fa49303b34d28309edd3).

2022-12-14 20:24 UTC, yantosca commented on src/Core/hcoio_read_std_mod.F90
> +       ! TODO: Merge warnings w/ verbose, and toggle with a simple on/off
Now removed in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 20:24 UTC, yantosca commented on src/Core/hco_error_mod.F90
> +       IF ( Err%LUN < 0 ) LUN = 6   ! ,,, or to stdout if file isn't open
Now removed in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 20:24 UTC, yantosca commented on src/Core/hco_error_mod.F90
> +    ! Check if "Verbose: 3" was set in the HEMCO_Config.rc file
Now removed in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 20:24 UTC, yantosca commented on src/Core/hco_error_mod.F90
> +!  TODO: Convert VERBOSE to a simple logical on/off switch.
Now removed in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 20:24 UTC, yantosca commented on src/Core/hco_error_mod.F90
> +! !DESCRIPTION: Returns true if the HEMCO verbose number is set to 3 or larger.
Now updated in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 20:24 UTC, yantosca commented on src/Core/hco_error_mod.F90
> +       !WarningLevel =  0
Now removed in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 20:24 UTC, yantosca commented on src/Core/hco_config_mod.F90
> +       !                    verb, warn, RC )
Now removed in 098f91ea3979eb4a39315803ea66756fda92a767

2022-12-14 21:16 UTC, msulprizio approved these changes

2022-12-22 21:09 UTC, yantosca commented
I have removed much of the prior logic in commits 824b07f0489bbf322ac77b650127c2d2071d62b2 and 78238dfc9e180d2a7f10e69763d00c284b9d1741.

Also, in commit https://github.com/geoschem/geos-chem/pull/1549/commits/0df54f6dc28b2abefa9d038c7f4935435ff2b547 I have added the `VerboseOnCores` setting to allow users to specify if they would like to send verbose output to the root core or to all cores (analogous to GEOS-Chem).

Integration tests running

2023-01-24 21:25 UTC, yantosca commented
I have merged the logfile cleanup updates to GEOS-Chem 14.1.0 and HEMCO 3.6.0.  New integration tests are running.

2023-02-07 18:38 UTC, merged