[WIP] Update IsModelLevel check for CESM and WRF-GC
geoschem/HEMCO pull request #244
Opened 2023-10-24 00:08 UTC by jimmielin

# This is testing-in-progress - please do not merge yet
Putting this up so it stays on the radar

### Name and Institution (Required)

Name: Haipeng Lin
Institution: Harvard U.

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://hemco.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### Describe the update

In HEMCO 3.7.x (via PR https://github.com/geoschem/HEMCO/pull/235), @nicholasbalasus and I introduced changes to the vertical regridding handling in HEMCO for accuracy and for removing legacy code.

However, this causes a regression in functionality for GEOS-Chem within CESM and WRF-GC as they can no longer vertically regrid emissions to their (dynamically set) model levels.

In `MODEL_CESM` and `MODEL_WRF`, `IsModelLevel` can never be `.true.` because models are dynamically set and thus no fixed input file is on "CESM/WRF model levels" at runtime. Thus the `IsModelLevel` variable in these models is interpreted to be "GEOS-Chem model levels" and a fixed set of GEOS-Chem level parameters is included in the file to regrid these to the CESM/WRF model grids.

Changes to the `Is_ModelLevel` subroutine has made it return `.false.` under CESM/WRF which causes HEMCO to attempt to read sigma levels from files which do not have these levels, e.g., AEIC19 inventory.

This update returns HEMCO in CESM/WRF to its original functionality with a more robust check of units (`level` or `GEOS-Chem level` will mean data is on GEOS-Chem levels). Sigma coordinates explicitly specified will still be handled correctly.

### Expected changes

No changes to GEOS-Chem full-chemistry benchmark.

Returns HEMCO vertical regridding behavior in CESM/WRF to pre-3.7.x behavior.

### Reference(s)

N/A

### Related Github Issue(s)

Steps to reproduce in CESM: clone CESM latest, manually checkout `[HEMCO]` external under `src/hemco/HEMCO` to versions 3.7.1. Run will fail due to AEIC19 inventory not containing proper sigma levels.

2023-10-25 15:13 UTC, lizziel commented
Thanks @jimmielin. Is this PR ready to merge or are you still working on it?

2023-10-26 17:09 UTC, jimmielin commented
Hi @lizziel I think it is ready but I'm waiting for Derecho to come back up so I can run final checks on this to make sure it works with both CAM-chem & GEOS-Chem. 

We're in no rush in bringing in HEMCO 3.7.x to CESM, but please let me know if there is a point release of 3.7.x in the works and this PR could go in there. If not then I can wait for whatever the next release is and update CESM to that.

2023-10-27 14:36 UTC, lizziel commented
There is now a HEMCO branch dev/no-diff-to-benchmark that we can merge this into as soon as it is ready.

2023-10-27 14:41 UTC, lizziel requested changes
The code looks good. Please consolidate all of the comments into one block within the CESM/WRF ifdef. Put all before the the IF LevUnit check so that the executed code isn't broken up by comments. That will make it easier to read. Thanks!

2023-12-18 15:04 UTC, msulprizio commented
@jimmielin Is this PR still a WIP or is it ready to merge?

2023-12-18 15:07 UTC, lizziel approved these changes

2023-12-18 15:12 UTC, jimmielin commented
Thanks @msulprizio this should be ready for merge. I'll remove the WIP flag.

2023-12-18 19:23 UTC, merged